Workflow
eleven032/Metronome pull request #5
Opened 2019-12-26 07:53 UTC by x566chen

GitHub page deploy action

2019-12-26 09:16 UTC, eleven032 requested changes

2019-12-26 09:16 UTC, eleven032 commented on .github/workflows/Build&Deploy.yml
>        with:
Action should be changed from push to merge

2019-12-27 01:23 UTC, bee0060 commented
Does the 17 commits all valid for other developers? If not, please combine them.

2019-12-27 01:26 UTC, bee0060 commented on build/asset-manifest.json
> +    "static/js/2.6541b97b.chunk.js",
Are names of chunks dynamic? 

If you build again, will these files names all change? 

If yes, do you really need to keep this in git?

2019-12-27 01:27 UTC, bee0060 commented
emm... I saw many files were generated by build, do you really want to keep them in git? why?

2019-12-27 03:59 UTC, merged